/**
 * Apply the VENDORED Better Auth schema (ADR-008 / ADR-010) deterministically.
 *
 *   pnpm --filter @numisma/web auth:apply
 *
 * Reads the checked-in `better-auth.schema.sql` (generated by the pinned
 * `@better-auth/cli@1.4.21`, no `@latest`) and applies it to AUTH_DATABASE_URL
 * through the node-postgres driver. Network-free and idempotent: the generated
 * `create table` / `create index` statements have no `IF NOT EXISTS`, so a
 * re-run raises "already exists" (42P07 / 42P06 / 42P07-class) — those are
 * caught and treated as no-ops, leaving every other error to surface loudly.
 *
 * This is the deterministic apply path for the auth store; `auth:migrate`
 * (also pinned) remains available as the CLI-driven alternative.
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { Pool } from "pg";

const HERE = dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = resolve(HERE, "./better-auth.schema.sql");

// "already exists" classes: duplicate_table, duplicate_object, duplicate_index.
const ALREADY_EXISTS = new Set(["42P07", "42710", "42P06"]);

/** Split the vendored SQL into individual statements (no string literals contain ';'). */
function statements(sql: string): string[] {
  return sql
    .split("\n")
    .filter((line) => !line.trimStart().startsWith("--"))
    .join("\n")
    .split(";")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

async function main(): Promise<void> {
  const connectionString = process.env.AUTH_DATABASE_URL;
  if (!connectionString) {
    throw new Error("AUTH_DATABASE_URL is not set");
  }

  const sql = await readFile(SCHEMA_PATH, "utf-8");
  const pool = new Pool({ connectionString });
  let created = 0;
  let skipped = 0;
  try {
    for (const statement of statements(sql)) {
      try {
        await pool.query(statement);
        created += 1;
      } catch (err: unknown) {
        const code =
          typeof err === "object" && err !== null && "code" in err
            ? String((err as { code: unknown }).code)
            : undefined;
        if (code && ALREADY_EXISTS.has(code)) {
          skipped += 1;
          continue; // idempotent: object already present
        }
        throw err;
      }
    }
    console.log(
      `[auth:apply] vendored Better Auth schema applied ` +
        `(${created} created, ${skipped} already present)`,
    );
  } finally {
    await pool.end();
  }
}

main().then(
  () => process.exit(0),
  (err: unknown) => {
    console.error(
      "[auth:apply] failed:",
      err instanceof Error ? err.message : err,
    );
    process.exit(1);
  },
);
